#!/usr/bin/env python3
"""
Build KDP hardcover (6x9) manuscript for Dunce to Midjourney Pro.

Source:  public/textbooks/kdp/dunce-to-midjourney-pro/dunce-to-midjourney-pro-kdp-6x9.html
         (generated by build-kdp-dunce-to-midjourney-pro-6x9.py)
Output:  public/textbooks/kdp/dunce-to-midjourney-pro/dunce-to-midjourney-pro-kdp-6x9-hardcover.html

Rules applied:
  1. Inherit from the paperback manuscript (not the source textbook directly)
  2. Widen the gutter margin from 0.75in to 0.875in for hardcover binding
  3. Retitle for hardcover manuscript mode
"""
from pathlib import Path
import re

ROOT = Path(__file__).parent
TITLE = "Dunce to Midjourney Pro"

SRC  = ROOT / "public/textbooks/kdp/dunce-to-midjourney-pro/dunce-to-midjourney-pro-kdp-6x9.html"
DEST = ROOT / "public/textbooks/kdp/dunce-to-midjourney-pro/dunce-to-midjourney-pro-kdp-6x9-hardcover.html"

GUTTER_HC  = "0.875in"
OUTSIDE_HC = "0.5in"


def bump_gutter(text: str) -> str:
    """Replace paperback gutter values with the wider hardcover gutter."""
    # Replace all left/right margin values that reference the PB gutter (0.75in in :left/:right)
    text = re.sub(
        r'(margin-right:\s*)0\.75in;(\s*\n\s*\}[\s\n]*@page :right)',
        r'\g<1>' + GUTTER_HC + r';\g<2>',
        text,
        count=1,
    )
    text = re.sub(
        r'(@page :right \{[^}]*margin-left:\s*)0\.75in;',
        r'\g<1>' + GUTTER_HC + ';',
        text,
        count=1,
    )
    return text


def retitle(text: str) -> str:
    return re.sub(
        r'<title>[^<]*</title>',
        f'<title>{TITLE} (6\u00d79 Hardcover Manuscript)</title>',
        text,
        count=1,
    )


def build() -> None:
    if not SRC.exists():
        raise FileNotFoundError(
            f"Paperback manuscript not found: {SRC}\n"
            "Run build-kdp-dunce-to-midjourney-pro-6x9.py first."
        )

    html = SRC.read_text(encoding="utf-8")
    html = bump_gutter(html)
    html = retitle(html)

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(html, encoding="utf-8")

    print(f"[ok] Built {DEST}")
    print(f"     Source: {SRC.stat().st_size:,} bytes -> Output: {DEST.stat().st_size:,} bytes")


if __name__ == "__main__":
    build()
