FROM python:3.12-slim

RUN pip install --no-cache-dir \
    flask==3.1.0 \
    kafka-python==2.0.2 \
    requests==2.32.3 \
    pyyaml==6.0.2 \
    elasticsearch==8.16.0 \
    prometheus-client==0.21.1 \
    flask-socketio==5.4.1 \
    eventlet==0.36.1 \
    pyjwt==2.9.0 \
    cryptography==44.0.0 \
    gunicorn==23.0.0

WORKDIR /app
COPY services/ ./services/

EXPOSE 8443 8080 8081 9090 9099
